command: ["uvicorn", "backend.main:app"]

resources:
  secret_db_host:
    type: secret
    scope: facturas-secrets
    key: DB_HOST
    permission: CAN_READ

  secret_db_name:
    type: secret
    scope: facturas-secrets
    key: DB_NAME
    permission: CAN_READ

  secret_db_user:
    type: secret
    scope: facturas-secrets
    key: DB_USER
    permission: CAN_READ

  secret_db_password:
    type: secret
    scope: facturas-secrets
    key: DB_PASSWORD
    permission: CAN_READ

  secret_db_httpath:
    type: secret
    scope: facturas-secrets
    key: HTTP_PATH
    permission: CAN_READ

  secret_db_access_token:
    type: secret
    scope: facturas-secrets
    key: ACCESS_TOKEN
    permission: CAN_READ

env:
  - name: DB_HOST
    valueFrom: "adb-7405615568530351.11.azuredatabricks.net"
  - name: DB_NAME
    valueFrom: "databricks_postgres"
  - name: DB_USER
    valueFrom: secret_db_user
  - name: DB_PASSWORD
    valueFrom: secret_db_password
  - name: HTTP_PATH
    valueFrom: "/sql/1.0/warehouses/605b873f22449da5"
  - name: ACCESS_TOKEN
    valueFrom: "dapi927b2dd86f775c5296eb785afff3053a"